### ISSUE TITLE
What is the practical task of the dll file?

### ISSUE THREAD

**Issue by SHUSTRIK-Milan** [pootis-network/gmod-discord-rpc#5]
What is the practical task of the dll file? If HTTP requests are banned by Discord, what does the DLL file do to get around this ban? Thanks in advance for the answer!

**Comment by thexkey** [comment]
the DLL files are used to communicate directly to the discord client if it is installed using RPC instead of the banned HTTP protocol, otherwise the DLL's do nothing at all.
